# mypaas.service=netdata
# mypaas.url=https://MYPAAS.YOURDOMAIN.COM/netdata
# mypaas.port=19999
# mypaas.volume=/proc:/host/proc:ro
# mypaas.volume=/sys:/host/sys:ro
# mypaas.volume=/var/run/docker.sock:/var/run/docker.sock:ro

# looks like I need these
#  --cap-add SYS_PTRACE \
#  --security-opt apparmor=unconfined \

FROM netdata/netdata
